<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
        <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
        <!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

        <!-- Note for MacCatalyst:
        The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
        When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
        The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
        either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
        <!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

        <OutputType>Exe</OutputType>
        <RootNamespace>ISAI.Lessons.Mobile</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <!-- https://github.com/CommunityToolkit/Maui/issues/2205 -->
        <NoWarn>XC0103</NoWarn>
        <MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>

        <!-- Display name -->
        <ApplicationTitle>Scottish Online Lessons</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>uk.co.isai.lessons.mobile.maui</ApplicationId>
        <ApplicationIdGuid>73048105-4e03-45ba-879d-dd173cd0db51</ApplicationIdGuid>

        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>

        <!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
        <WindowsPackageType>None</WindowsPackageType>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Include="Resources\AppIcon\appicon.png">
          <Color>#FFFFFF</Color>
        </MauiIcon>
        <MauiSplashScreen Include="Resources\Splash\spash.png">
          <Color>#FFFFFF</Color>
        </MauiSplashScreen>

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128"/>

        <!-- Images -->
        <MauiImage Include="Resources\Images\*"/>
        <MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185"/>

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*"/>

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2"/>
        <PackageReference Include="CommunityToolkit.Maui" Version="9.1.0"/>
        <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.8"/>
        <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.10"/>
        <PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ISAI.Lessons.Core\ISAI.Lessons.Core.csproj" />
      <ProjectReference Include="..\..\ISAI.Lessons.Models\ISAI.Lessons.Models.csproj" />
    </ItemGroup>

    <ItemGroup>
      <MauiXaml Update="Pages\AboutPage.xaml">
        <SubType>Designer</SubType>
        <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
      <MauiXaml Update="Pages\LaunchPage.xaml">
        <SubType>Designer</SubType>
        <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
      <MauiXaml Update="Pages\LessonDownloadsPage.xaml">
        <SubType>Designer</SubType>
        <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
      <MauiXaml Update="Pages\LessonGroupPage.xaml">
        <SubType>Designer</SubType>
        <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
      <MauiXaml Update="Pages\LessonPage.xaml">
        <SubType>Designer</SubType>
        <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
      <MauiXaml Update="Pages\LessonsPage.xaml">
        <SubType>Designer</SubType>
        <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
      <MauiXaml Update="Pages\LoginPage.xaml">
        <SubType>Designer</SubType>
        <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
      <MauiXaml Update="Pages\VideoPage.xaml">
        <SubType>Designer</SubType>
        <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Pages\AboutPage.xaml.cs">
        <DependentUpon>AboutPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Pages\LaunchPage.xaml.cs">
        <DependentUpon>LaunchPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Pages\LessonDownloadsPage.xaml.cs">
        <DependentUpon>LessonDownloadsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Pages\LessonGroupPage.xaml.cs">
        <DependentUpon>LessonGroupPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Pages\LessonPage.xaml.cs">
        <DependentUpon>LessonPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Pages\LessonsPage.xaml.cs">
        <DependentUpon>LessonsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Pages\LoginPage.xaml.cs">
        <DependentUpon>LoginPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Pages\VideoPage.xaml.cs">
        <DependentUpon>VideoPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
      <PackageReference Include="AndHUD" Version="2.0.2" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
      <PackageReference Include="BTProgressHUD" Version="2.1.1" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-maccatalyst'">
      <PackageReference Include="BTProgressHUD" Version="2.1.1" />
    </ItemGroup>

</Project>
