<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <TargetFrameworks>net9.0;netstandard2.0;</TargetFrameworks>
		<IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">false</IsTrimmable>
	</PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <TargetFrameworks>net9.0;netstandard2.0;</TargetFrameworks>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.5.0" />
  </ItemGroup>

</Project> 
