<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <MtouchEnableSGenConc>true</MtouchEnableSGenConc>
    <ProvisioningType>automatic</ProvisioningType>
    <TargetFrameworks>net7.0-android;net7.0-ios</TargetFrameworks>
    <UseMaui>True</UseMaui>
    <ImplicitUsings>enable</ImplicitUsings>
    <SingleProject>true</SingleProject>
    <AssemblyTitle>ISAI.Lessons.Mobile.iOS</AssemblyTitle>
    <Product>ISAI.Lessons.Mobile.iOS</Product>
    <Copyright>Copyright ©  2014</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <MtouchArch>x86_64</MtouchArch>
    <MtouchLink>None</MtouchLink>
    <MtouchDebug>true</MtouchDebug>
    <CodesignKey>iPhone Developer</CodesignKey>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <MtouchLink>None</MtouchLink>
    <MtouchArch>x86_64</MtouchArch>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <MtouchArch>ARM64</MtouchArch>
    <CodesignKey>iPhone Developer</CodesignKey>
    <MtouchDebug>true</MtouchDebug>
    <MtouchLink>None</MtouchLink>
    <MtouchInterpreter>-all</MtouchInterpreter>
    <CodesignProvision>Lessons Development</CodesignProvision>
    <MtouchSdkVersion>14.5</MtouchSdkVersion>
    <IntermediateOutputPath></IntermediateOutputPath>
    <DebugSymbols></DebugSymbols>
    <DebugType></DebugType>
    <Optimize></Optimize>
    <OutputPath></OutputPath>
    <DefineConstants></DefineConstants>
    <WarningLevel></WarningLevel>
    <TreatWarningsAsErrors></TreatWarningsAsErrors>
    <DocumentationFile></DocumentationFile>
    <ConsolePause>true</ConsolePause>
    <ExternalConsole>false</ExternalConsole>
    <Commandlineparameters></Commandlineparameters>
    <RunWithWarnings>true</RunWithWarnings>
    <AssemblyName></AssemblyName>
    <SignAssembly></SignAssembly>
    <DelaySign>false</DelaySign>
    <PublicSign>false</PublicSign>
    <AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
    <NoWarn></NoWarn>
    <AllowUnsafeBlocks></AllowUnsafeBlocks>
    <CheckForOverflowUnderflow></CheckForOverflowUnderflow>
    <LangVersion>Default</LangVersion>
    <NoStdLib></NoStdLib>
    <PlatformTarget>anycpu</PlatformTarget>
    <WarningsNotAsErrors></WarningsNotAsErrors>
    <Nullable></Nullable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <MtouchArch>ARM64</MtouchArch>
    <CodesignKey>iPhone Developer</CodesignKey>
    <MtouchLink>SdkOnly</MtouchLink>
    <IntermediateOutputPath></IntermediateOutputPath>
    <DebugSymbols></DebugSymbols>
    <DebugType></DebugType>
    <Optimize></Optimize>
    <OutputPath></OutputPath>
    <DefineConstants></DefineConstants>
    <WarningLevel></WarningLevel>
    <TreatWarningsAsErrors></TreatWarningsAsErrors>
    <DocumentationFile></DocumentationFile>
    <ConsolePause>true</ConsolePause>
    <ExternalConsole>false</ExternalConsole>
    <Commandlineparameters></Commandlineparameters>
    <RunWithWarnings>true</RunWithWarnings>
    <AssemblyName></AssemblyName>
    <SignAssembly></SignAssembly>
    <DelaySign>false</DelaySign>
    <PublicSign>false</PublicSign>
    <AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
    <NoWarn></NoWarn>
    <AllowUnsafeBlocks></AllowUnsafeBlocks>
    <CheckForOverflowUnderflow></CheckForOverflowUnderflow>
    <LangVersion>Default</LangVersion>
    <NoStdLib></NoStdLib>
    <PlatformTarget>anycpu</PlatformTarget>
    <WarningsNotAsErrors></WarningsNotAsErrors>
    <Nullable></Nullable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <IntermediateOutputPath></IntermediateOutputPath>
    <DebugSymbols></DebugSymbols>
    <DebugType></DebugType>
    <Optimize></Optimize>
    <OutputPath></OutputPath>
    <DefineConstants></DefineConstants>
    <WarningLevel></WarningLevel>
    <TreatWarningsAsErrors></TreatWarningsAsErrors>
    <DocumentationFile></DocumentationFile>
    <ConsolePause>true</ConsolePause>
    <ExternalConsole>false</ExternalConsole>
    <Commandlineparameters></Commandlineparameters>
    <RunWithWarnings>true</RunWithWarnings>
    <AssemblyName></AssemblyName>
    <SignAssembly></SignAssembly>
    <DelaySign>false</DelaySign>
    <PublicSign>false</PublicSign>
    <AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
    <NoWarn></NoWarn>
    <AllowUnsafeBlocks></AllowUnsafeBlocks>
    <CheckForOverflowUnderflow></CheckForOverflowUnderflow>
    <LangVersion>Default</LangVersion>
    <NoStdLib></NoStdLib>
    <PlatformTarget>anycpu</PlatformTarget>
    <WarningsNotAsErrors></WarningsNotAsErrors>
    <Nullable></Nullable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <IntermediateOutputPath></IntermediateOutputPath>
    <DebugSymbols></DebugSymbols>
    <DebugType></DebugType>
    <Optimize></Optimize>
    <OutputPath></OutputPath>
    <DefineConstants></DefineConstants>
    <WarningLevel></WarningLevel>
    <TreatWarningsAsErrors></TreatWarningsAsErrors>
    <DocumentationFile></DocumentationFile>
    <ConsolePause>true</ConsolePause>
    <ExternalConsole>false</ExternalConsole>
    <Commandlineparameters></Commandlineparameters>
    <RunWithWarnings>true</RunWithWarnings>
    <AssemblyName></AssemblyName>
    <SignAssembly></SignAssembly>
    <DelaySign>false</DelaySign>
    <PublicSign>false</PublicSign>
    <AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
    <NoWarn></NoWarn>
    <AllowUnsafeBlocks></AllowUnsafeBlocks>
    <CheckForOverflowUnderflow></CheckForOverflowUnderflow>
    <LangVersion>Default</LangVersion>
    <NoStdLib></NoStdLib>
    <PlatformTarget>anycpu</PlatformTarget>
    <WarningsNotAsErrors></WarningsNotAsErrors>
    <Nullable></Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="2.0.0" />
    <PackageReference Include="Plugin.MediaManager.Forms" Version="1.2.2" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116">
    </PackageReference>
    <PackageReference Include="Xam.Plugins.DownloadManager" Version="1.4.0">
    </PackageReference>
    <PackageReference Include="Plugin.DeviceOrientation" Version="1.0.7">
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.2" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ISAI.Lessons.Core\ISAI.Lessons.Core.csproj" />
    <ProjectReference Include="..\..\ISAI.Lessons.Models\ISAI.Lessons.Models.csproj" />
    <ProjectReference Include="..\ISAI.Lessons.Mobile\ISAI.Lessons.Mobile.csproj" />
  </ItemGroup>
</Project>