// <auto-generated />
namespace ISAI.Lessons.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Addedemailpendingnotifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedemailpendingnotifications));
        
        string IMigrationMetadata.Id
        {
            get { return "202412310945439_Added email pending notifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
