// <auto-generated />
namespace ISAI.Lessons.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TutorSubjectUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TutorSubjectUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202503051008047_Tutor Subject User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
