<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TargetFrameworks>net9.0;netstandard2.0;</TargetFrameworks>
	  <IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">false</IsTrimmable>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TargetFrameworks>net9.0;netstandard2.0;</TargetFrameworks>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.1" />
    <PackageReference Include="Microsoft.Graph" Version="5.65.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ISAI.Lessons.Models\ISAI.Lessons.Models.csproj" />
  </ItemGroup>

</Project>
