<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AndroidResgenFile>Resources\Resource.designer.cs</AndroidResgenFile>
    <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
    <TargetFrameworks>net7.0-android;net7.0-ios</TargetFrameworks>
    <UseMaui>True</UseMaui>
    <ImplicitUsings>enable</ImplicitUsings>
    <SingleProject>true</SingleProject>
    <AssemblyTitle>ISAI.Lessons.Mobile.Android</AssemblyTitle>
    <Product>ISAI.Lessons.Mobile.Android</Product>
    <Copyright>Copyright ©  2014</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <AndroidKeyStore>true</AndroidKeyStore>
    <AndroidSigningKeyStore>C:\Development\Lessons\Keys\uteach.keystore</AndroidSigningKeyStore>
    <AndroidSigningStorePass>uteach123@@**</AndroidSigningStorePass>
    <AndroidSigningKeyPass>uteach123@@**</AndroidSigningKeyPass>
    <AndroidSigningKeyAlias>uteach</AndroidSigningKeyAlias>
    <AndroidLinkMode>None</AndroidLinkMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Plugin.CurrentActivity">
      <Version>2.1.0.4</Version>
    </PackageReference>
    <PackageReference Include="Plugin.MediaManager.Forms">
      <Version>1.0.8</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.7.335</Version>
    </PackageReference>
    <PackageReference Include="Plugin.DeviceOrientation">
      <Version>1.0.7</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.2" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.2" />
    <PackageReference Include="CommunityToolkit.Maui" Version="5.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ISAI.Lessons.Core\ISAI.Lessons.Core.csproj" />
    <ProjectReference Include="..\..\ISAI.Lessons.Models\ISAI.Lessons.Models.csproj" />
    <ProjectReference Include="..\ISAI.Lessons.Mobile\ISAI.Lessons.Mobile.csproj" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties TriggeredFromHotReload="False" />
    </VisualStudio>
  </ProjectExtensions>
</Project>