<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;</TargetFrameworks>
		

		<OutputType>Exe</OutputType>
		<RootNamespace>ISAI.Lessons.Mobile</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Scottish Online Lessons</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>uk.co.isai.uteachlessons.pupil.ios</ApplicationId>
		<ApplicationIdGuid>73048105-4e03-45ba-879d-dd173cd0db51</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">31.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net9.0-ios' and '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<CodesignEntitlement>Entitlements.plist</CodesignEntitlement>
		<CodesignKey>Apple Distribution: ISAI Technologies Ltd (T5X7RSN9L7)</CodesignKey>
		<CodesignProvision>Lesson Distribution</CodesignProvision>
		<MtouchInterpreter>all</MtouchInterpreter>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->

		<!-- Splash Screen -->

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Platforms\Android\Resources\xml\network_security_config.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="12.2.0" />
		<PackageReference Include="EmbedIO" Version="3.5.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.110" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.9" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="Syncfusion.Maui.ListView" Version="31.1.22" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\ISAI.Lessons.Core\ISAI.Lessons.Core.csproj" />
	  <ProjectReference Include="..\..\ISAI.Lessons.Models\ISAI.Lessons.Models.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\AboutPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LaunchPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LessonDownloadsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LessonGroupPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LessonPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LessonsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LoginPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\VideoPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
	  <PackageReference Include="BTProgressHUD">
	    <Version>2.1.1</Version>
	  </PackageReference>
	</ItemGroup>

	
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
	  <PackageReference Include="AndHUD">
	    <Version>2.0.2</Version>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <MauiIcon Include="Resources\AppIcon\appicon.png">
	    <Color>#FFFFFF</Color>
	  </MauiIcon>
	</ItemGroup>

	<ItemGroup>
	  <MauiSplashScreen Include="Resources\Splash\spash.png">
	    <Color>#FFFFFF</Color>
	  </MauiSplashScreen>
	</ItemGroup>

</Project>
