<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Plugin.MediaManager.Forms" Version="1.0.8" />
    <PackageReference Include="sqlite-net-pcl" Version="1.7.335" />
    <PackageReference Include="Xam.Plugin.Hud" Version="1.0.5" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="1.1.0" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime.Azure.Authentication" Version="2.4.1" />
    <PackageReference Include="Plugin.DeviceOrientation" Version="1.0.7" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.2.0" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ISAI.Lessons.Core\ISAI.Lessons.Core.csproj" />
    <ProjectReference Include="..\..\ISAI.Lessons.Models\ISAI.Lessons.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\LessonsPage.xaml.cs">
      <DependentUpon>LessonsPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Views\LaunchPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\LessonDownloadsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\LessonGroupPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\LessonPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\VideoPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Convertor\" />
    <Folder Include="Models\Messages\" />
  </ItemGroup>
</Project>