<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	    <TargetFrameworks>net8.0-android;net8.0-ios;</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>ISAI.Lessons.Mobile.Maui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>Scottish Online Lessons</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>uk.co.isai.lessons.mobile.maui</ApplicationId>
		<ApplicationIdGuid>73048105-4e03-45ba-879d-dd173cd0db51</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">29.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup>
		<UseInterpreter Condition="'$(UseInterpreter)' == '' and '$(Configuration)' == 'Release'">True</UseInterpreter>
		<MtouchLink Condition="'$(MtouchLink)' == '' and '$(Configuration)' == 'Release' and '$(UseInterpreter)' == 'true'">None</MtouchLink>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	  <CodesignKey>iPhone Developer</CodesignKey>
	  <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
	  <CodesignProvision></CodesignProvision>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	  <CodesignKey>Apple Distribution: ISAI Technologies Ltd (T5X7RSN9L7)</CodesignKey>
	  <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
	  <CodesignProvision>Lesson Distribution</CodesignProvision>
	</PropertyGroup>

	<!--	 <PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
        <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    </PropertyGroup>-->
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
	  <WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	  <CodesignProvision>Lesson Distribution</CodesignProvision>
	  <CodesignKey>Apple Distribution: ISAI Technologies Ltd (T5X7RSN9L7)</CodesignKey>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
	  <DebugSymbols>true</DebugSymbols>
	  <WarningLevel>4</WarningLevel>
	</PropertyGroup>
		<ItemGroup>

	  <None Remove="Resources\AppIcon\appicon.png" />
	  <None Remove="Resources\Images\logo.png" />
	  <None Remove="Resources\Splash\splash.png" />
	  <None Remove="Platforms\iOS\Helpers\" />
	  <None Remove="Platforms\iOS\Helpers\CrossDownloadManager\" />
	</ItemGroup>

	<ItemGroup>
		<!-- App Icon -->
		 <MauiIcon Include="Resources\AppIcon\appicon.png" Color="#FFFFFF" />
		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\spash.png" Color="#FFFFFF" />
		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>




	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="5.2.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.5" />
		<PackageReference Include="Microsoft.AppCenter" Version="5.0.2" />
		<PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.2" />
		<PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.61" />
		<PackageReference Include="BTProgressHUD" Version="2.1.1" Condition="'$(TargetFramework)' == 'net8.0-ios'" />
		<PackageReference Include="AndHUD" Version="2.0.2" Condition="'$(TargetFramework)' == 'net8.0-android'" />
	
	</ItemGroup>

	


	<ItemGroup>
	  <ProjectReference Include="..\ISAI.Lessons.Core\ISAI.Lessons.Core.csproj" />
	  <ProjectReference Include="..\ISAI.Lessons.Models\ISAI.Lessons.Models.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\AboutPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\LaunchPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\LessonDownloadsPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\LessonGroupPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\LessonPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\LessonsPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\LoginPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\VideoPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\AboutPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LaunchPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LessonDownloadsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LessonGroupPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LessonPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LessonsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LoginPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\VideoPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>



	<ItemGroup>
	  <Folder Include="Platforms\iOS\Helpers\" />
	  <Folder Include="Platforms\iOS\Helpers\CrossDownloadManager\" />
	</ItemGroup>



	<ItemGroup>
	  <AndroidNativeLibrary Remove="C:\Users\craig\.nuget\packages\videolan.libvlc.android\3.5.3\build\android-armv7\libvlc.so" />
	</ItemGroup>



	<ItemGroup>
	  <AndroidNativeLibrary Remove="C:\Users\craig\.nuget\packages\videolan.libvlc.android\3.5.3\build\android-armv7\libc++_shared.so" />
	</ItemGroup>



	<ItemGroup>
	  <AndroidNativeLibrary Remove="C:\Users\craig\.nuget\packages\videolan.libvlc.android\3.5.3\build\android-armv8\libvlc.so" />
	</ItemGroup>



	<ItemGroup>
	  <AndroidNativeLibrary Remove="C:\Users\craig\.nuget\packages\videolan.libvlc.android\3.5.3\build\android-armv8\libc++_shared.so" />
	</ItemGroup>



	<ItemGroup>
	  <AndroidNativeLibrary Remove="C:\Users\craig\.nuget\packages\videolan.libvlc.android\3.5.3\build\android-x86\libvlc.so" />
	</ItemGroup>



	<ItemGroup>
	  <AndroidNativeLibrary Remove="C:\Users\craig\.nuget\packages\videolan.libvlc.android\3.5.3\build\android-x86\libc++_shared.so" />
	</ItemGroup>



	<ItemGroup>
	  <AndroidNativeLibrary Remove="C:\Users\craig\.nuget\packages\videolan.libvlc.android\3.5.3\build\android-x86_64\libvlc.so" />
	</ItemGroup>



	<ItemGroup>
	  <AndroidNativeLibrary Remove="C:\Users\craig\.nuget\packages\videolan.libvlc.android\3.5.3\build\android-x86_64\libc++_shared.so" />
	</ItemGroup>

</Project>
